<?php


/**
 * RootLabs POS uses custom operational tables for POS data.
 * These database calls are intentional and isolated in repository/service layers.
 *
 * rootlabs-pos-pro-w2a-db-intentional
 *
 * phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery
 * phpcs:disable WordPress.DB.DirectDatabaseQuery.NoCaching
 * phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
 * phpcs:disable WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
 * phpcs:disable WordPress.DB.PreparedSQLPlaceholders.ReplacementsWrongNumber
 * phpcs:disable PluginCheck.Security.DirectDB.UnescapedDBParameter
 */

namespace MXPOSPro\Sales;

defined('ABSPATH') || exit;

use MXPOSPro\Cash\CashSessionService;
use MXPOSPro\Cash\CashMovementService;
use MXPOSPro\Payments\PaymentMethodRepository;
use WP_Error;

class PaymentService
{
    public const MAX_PAYMENT_CLIENT_REQUEST_ID_LENGTH = 100;
    public const PAYMENT_TOLERANCE = 0.01;

    private SaleRepository $saleRepo;
    private CashSessionService $sessionService;
    private CashMovementService $cashMovementService;
    private PaymentMethodRepository $methodRepo;

    public function __construct(
        SaleRepository $saleRepo,
        CashSessionService $sessionService,
        CashMovementService $cashMovementService
    ) {
        $this->saleRepo            = $saleRepo;
        $this->sessionService      = $sessionService;
        $this->cashMovementService = $cashMovementService;
        $this->methodRepo          = new PaymentMethodRepository();
    }

    public function process_payment(int $userId, int $saleId, array $payload): array|WP_Error
    {
        if ($userId <= 0) {
            return new WP_Error(
                'mx_pos_invalid_user',
                __('Invalid user.', 'mx-pos-pro'),
                ['status' => 400]
            );
        }

        if (! current_user_can('mx_pos_sell')) {
            return new WP_Error(
                'mx_pos_sell_forbidden',
                __('You do not have permission to sell.', 'mx-pos-pro'),
                ['status' => 403]
            );
        }

        $sessionResult = $this->sessionService->get_current_session($userId);

        if (! $sessionResult['has_open_session'] || $sessionResult['session'] === null) {
            return new WP_Error(
                'mx_pos_no_open_session',
                __('No open session found. Open a session before processing payments.', 'mx-pos-pro'),
                ['status' => 409]
            );
        }

        $session   = $sessionResult['session'];
        $sessionId = (int) $session['id'];

        if (! isset($payload['payment_method']) || ! is_string($payload['payment_method'])) {
            return new WP_Error(
                'mx_pos_invalid_payment_method',
                __('payment_method is required.', 'mx-pos-pro'),
                ['status' => 400]
            );
        }

        $paymentMethodSlug = $payload['payment_method'];

        $method = $this->methodRepo->get_by_slug($paymentMethodSlug);

        if ($method === null || ! (int) ($method['is_active'] ?? 0)) {
            return new WP_Error(
                'mx_pos_invalid_payment_method',
                __('The selected payment method is not available.', 'mx-pos-pro'),
                ['status' => 400]
            );
        }

        if (! isset($payload['client_request_id']) || ! is_string($payload['client_request_id'])) {
            return new WP_Error(
                'mx_pos_missing_client_request_id',
                __('client_request_id is required.', 'mx-pos-pro'),
                ['status' => 400]
            );
        }

        $paymentClientRequestId = trim($payload['client_request_id']);

        if ($paymentClientRequestId === '') {
            return new WP_Error(
                'mx_pos_missing_client_request_id',
                __('client_request_id cannot be empty.', 'mx-pos-pro'),
                ['status' => 400]
            );
        }

        if (mb_strlen($paymentClientRequestId) > self::MAX_PAYMENT_CLIENT_REQUEST_ID_LENGTH) {
            return new WP_Error(
                'mx_pos_invalid_client_request_id',
                sprintf(
                    /* translators: %d is a dynamic value generated by the plugin. */
                    __('client_request_id must not exceed %d characters.', 'mx-pos-pro'),
                    self::MAX_PAYMENT_CLIENT_REQUEST_ID_LENGTH
                ),
                ['status' => 400]
            );
        }

        $sale = $this->saleRepo->get_by_id($saleId);

        if ($sale === null) {
            return new WP_Error(
                'mx_pos_sale_not_found',
                __('Sale not found.', 'mx-pos-pro'),
                ['status' => 404]
            );
        }

        if ((int) $sale['session_id'] !== $sessionId) {
            return new WP_Error(
                'mx_pos_sale_not_owned',
                __('This sale belongs to a different session.', 'mx-pos-pro'),
                ['status' => 403]
            );
        }

        if ($sale['status'] !== 'pending') {
            return new WP_Error(
                'mx_pos_sale_already_paid',
                __('This order has already been paid.', 'mx-pos-pro'),
                ['status' => 409]
            );
        }

        $order = wc_get_order((int) $sale['wc_order_id']);

        if (! $order instanceof \WC_Order) {
            return new WP_Error(
                'mx_pos_order_not_found',
                __('Associated WooCommerce order not found.', 'mx-pos-pro'),
                ['status' => 404]
            );
        }

        if ($order->get_status() !== 'pending') {
            return new WP_Error(
                'mx_pos_sale_already_paid',
                __('This order has already been paid or is in a non-pending state.', 'mx-pos-pro'),
                ['status' => 409]
            );
        }

        $existingPayment = $order->get_meta('_mx_pos_payment_completed', true);

        if ($existingPayment === 'yes') {
            return new WP_Error(
                'mx_pos_sale_already_paid',
                __('This order has already been paid.', 'mx-pos-pro'),
                ['status' => 409]
            );
        }

        $existingPaymentRequest = $order->get_meta('_mx_pos_payment_client_request_id', true);

        if ($existingPaymentRequest !== '' && $existingPaymentRequest !== null && $existingPaymentRequest !== false) {
            $decodedSummary = $this->decode_payment_summary($sale['payment_summary'] ?? null);
            $paymentInfo    = $decodedSummary['payment'] ?? [];

            return $this->build_response($sale, $order, $paymentInfo);
        }

        $orderTotal = (float) $order->get_total();
        $methodType = $method['payment_type'] ?? 'other';

        $paymentLines = [];
        $isMixed = ($methodType === 'mixed' && ! empty($payload['payment_lines']) && is_array($payload['payment_lines']));

        if ($isMixed) {
            return $this->process_mixed_payment(
                $userId, $sessionId, $sale, $saleId, $order, $orderTotal,
                $method, $payload, $paymentClientRequestId
            );
        }

        return $this->process_simple_payment(
            $userId, $sessionId, $sale, $saleId, $order, $orderTotal,
            $method, $payload, $paymentClientRequestId
        );
    }

    private function process_simple_payment(
        int $userId, int $sessionId, array $sale, int $saleId,
        \WC_Order $order, float $orderTotal, array $method, array $payload, string $clientRequestId
    ): array|WP_Error {
        $paymentMethodSlug = $method['slug'];
        $methodName        = $method['name'];
        $methodType        = $method['payment_type'] ?? 'other';
        $methodId          = (int) $method['id'];
        $affectsCash       = (bool) ((int) ($method['affects_cash_register'] ?? 0));

        $amountReceived = $orderTotal;
        $change         = 0.0;
        $cardReference  = null;
        $cardFee        = null;

        if ($methodType === 'cash' || $affectsCash) {
            if (! isset($payload['amount_received']) || ! is_numeric($payload['amount_received'])) {
                return new WP_Error(
                    'mx_pos_missing_amount_received',
                    __('amount_received is required for this payment method.', 'mx-pos-pro'),
                    ['status' => 400]
                );
            }

            $amountReceived = (float) $payload['amount_received'];

            if ($amountReceived <= 0) {
                return new WP_Error(
                    'mx_pos_invalid_amount_received',
                    __('amount_received must be a positive number.', 'mx-pos-pro'),
                    ['status' => 400]
                );
            }

            if ($amountReceived < $orderTotal - 0.00001) {
                return new WP_Error(
                    'mx_pos_insufficient_payment',
                    sprintf(
                        /* translators: %1$s, %2$s are dynamic values generated by the plugin. */
                        __('Insufficient amount. Received: %1$s, Total: %2$s.', 'mx-pos-pro'),
                        $this->formatDecimal($amountReceived),
                        $this->formatDecimal($orderTotal)
                    ),
                    ['status' => 400]
                );
            }

            $change = $amountReceived - $orderTotal;
        }

        if ($methodType === 'card') {
            if (isset($payload['card_reference']) && is_string($payload['card_reference'])) {
                $ref = trim($payload['card_reference']);
                if ($ref !== '' && mb_strlen($ref) <= 100) {
                    $cardReference = $ref;
                }
            }

            $cardFee = $this->calculate_card_fee($method, $orderTotal);
        }

        if ($allowRef = (bool) ((int) ($method['allow_reference'] ?? 0))) {
            if (isset($payload['card_reference']) && is_string($payload['card_reference'])) {
                $ref = trim($payload['card_reference']);
                if ($ref !== '' && mb_strlen($ref) <= 100) {
                    $cardReference = $ref;
                }
            }
        }

        $transactionId = 'pos-' . $paymentMethodSlug . '-' . $saleId;

        $paymentMethodTitle = $this->resolve_payment_method_title($method);
        $this->set_order_payment_meta($order, $paymentMethodSlug, $paymentMethodTitle, $clientRequestId, $transactionId);

        try {
            $this->complete_pos_order($order, $transactionId);
        } catch (\Exception $e) {
            $order->delete_meta_data('_mx_pos_payment_completed');
            $order->delete_meta_data('_mx_pos_payment_method');
            $order->delete_meta_data('_mx_pos_payment_method_title');
            $order->delete_meta_data('_mx_pos_payment_client_request_id');
            $order->delete_meta_data('_mx_pos_payment_transaction_id');
            $order->delete_meta_data('metodo_pago');
            $order->delete_meta_data('metodo_pago_nombre');
            $order->save();

            return new WP_Error(
                'mx_pos_payment_complete_failed',
                __('Payment could not be completed. Please try again.', 'mx-pos-pro'),
                ['status' => 500]
            );
        }

        $paidAt = $order->get_date_paid()
            ? $order->get_date_paid()->format('c')
            : current_time('c');

        $order->add_order_note(
            sprintf(
                $change > 0
                    /* translators: %1$s, %2$s, %3$s are dynamic values generated by the plugin. */
                    ? __('POS payment: %1$s — $%2$s received, $%3$s change.', 'mx-pos-pro')
                    /* translators: %1$s, %2$s are dynamic values generated by the plugin. */
                    : __('POS payment: %1$s — $%2$s.', 'mx-pos-pro'),
                $methodName,
                $this->formatDecimal($amountReceived),
                $this->formatDecimal($change)
            )
        );

        $order->save();

        $paymentInfo = [
            'method'          => $paymentMethodSlug,
            'method_name'     => $methodName,
            'amount_received' => $this->formatDecimal($amountReceived),
            'change'          => $this->formatDecimal($change),
            'card_reference'  => $cardReference,
            'card_fee'        => $cardFee !== null ? $this->formatDecimal($cardFee) : null,
            'card_fee_total'  => $cardFee !== null ? $this->formatDecimal($cardFee) : null,
            'transaction_id'  => $transactionId,
            'paid_at'         => $paidAt,
            'cashier_id'      => $userId,
            'session_id'      => $sessionId,
        ];

        $this->write_order_payment(
            $saleId, $methodId, $orderTotal,
            $amountReceived, $change, $cardReference, $transactionId,
            $clientRequestId
        );

        $this->finalize_payment($sale, $saleId, $order, $paymentInfo, $sessionId, $userId);

        if ($affectsCash) {
            $this->record_cash_movement(
                $sessionId, $userId, $orderTotal - $change,
                (string) $order->get_order_number(),
                $clientRequestId
            );
        }

        $this->saleRepo->create_log([
            'sale_id'    => $saleId,
            'event_type' => 'payment_received',
            'message'    => sprintf(
                /* translators: %1$s, %2$s are dynamic values generated by the plugin. */
                __('Payment received: %1$s — Order #%2$s.', 'mx-pos-pro'),
                $methodName,
                $order->get_order_number()
            ),
            'created_by' => $userId,
        ]);

        $sale = $this->saleRepo->get_by_id($saleId);

        return $this->build_response($sale ?? [
            'id'              => $saleId,
            'session_id'      => $sessionId,
            'cashier_id'      => $userId,
            'created_at'      => current_time('mysql'),
            'payment_summary' => '',
        ], $order, $paymentInfo);
    }

    private function process_mixed_payment(
        int $userId, int $sessionId, array $sale, int $saleId,
        \WC_Order $order, float $orderTotal, array $method, array $payload, string $clientRequestId
    ): array|WP_Error {
        $paymentLines = $payload['payment_lines'];

        if (empty($paymentLines)) {
            return new WP_Error(
                'mx_pos_mixed_no_lines',
                __('payment_lines required for mixed payment.', 'mx-pos-pro'),
                ['status' => 400]
            );
        }

        $normalizedLines = [];
        $lineSum         = 0.0;
        $totalCardFee    = 0.0;
        $cashLineAmount  = 0.0;
        $change          = 0.0;

        foreach ($paymentLines as $i => $line) {
            $lineSlug = $line['method'] ?? '';
            $lineAmount = (float) ($line['amount'] ?? 0);

            if ($lineAmount <= 0) {
                return new WP_Error(
                    'mx_pos_invalid_line_amount',
                    /* translators: %d is a dynamic value generated by the plugin. */
                    sprintf(__('Payment line %d: amount must be positive.', 'mx-pos-pro'), $i + 1),
                    ['status' => 400]
                );
            }

            $lineMethod = $this->methodRepo->get_by_slug($lineSlug);

            if ($lineMethod === null || ! (int) ($lineMethod['is_active'] ?? 0)) {
                return new WP_Error(
                    'mx_pos_invalid_line_method',
                    /* translators: %d is a dynamic value generated by the plugin. */
                    sprintf(__('Payment line %d: method not available.', 'mx-pos-pro'), $i + 1),
                    ['status' => 400]
                );
            }

            if (($lineMethod['payment_type'] ?? '') === 'mixed') {
                return new WP_Error(
                    'mx_pos_nested_mixed',
                    __('Mixed payment cannot contain another mixed payment.', 'mx-pos-pro'),
                    ['status' => 400]
                );
            }

            $ref = null;
            if (isset($line['reference']) && is_string($line['reference']) && $line['reference'] !== '') {
                $ref = sanitize_text_field($line['reference']);
            }

            $lineFee = null;
            if (($lineMethod['payment_type'] ?? '') === 'card') {
                $lineFee = $this->calculate_card_fee($lineMethod, $lineAmount);
                if ($lineFee !== null) {
                    $totalCardFee += $lineFee;
                }
            }

            $normalized = [
                'method'                => $lineSlug,
                'method_id'             => (int) $lineMethod['id'],
                'method_name'           => $lineMethod['name'],
                'amount'                => $lineAmount,
                'reference'             => $ref,
                'card_fee'              => $lineFee !== null ? $this->formatDecimal($lineFee) : null,
                'affects_cash_register'  => (bool) ((int) ($lineMethod['affects_cash_register'] ?? 0)),
            ];

            $normalizedLines[] = $normalized;
            $lineSum += $lineAmount;

            if ($normalized['affects_cash_register']) {
                $cashLineAmount += $lineAmount;
            }
        }

        $diff = abs($lineSum - $orderTotal);
        if ($diff > self::PAYMENT_TOLERANCE * 10) {
            return new WP_Error(
                'mx_pos_insufficient_payment',
                sprintf(
                    /* translators: %1$s, %2$s are dynamic values generated by the plugin. */
                    __('Insufficient payment. Total paid: %1$s, Order total: %2$s.', 'mx-pos-pro'),
                    $this->formatDecimal($lineSum),
                    $this->formatDecimal($orderTotal)
                ),
                ['status' => 400]
            );
        }

        if ($lineSum > $orderTotal + 0.001) {
            $excess = $lineSum - $orderTotal;
            if ($cashLineAmount >= $excess) {
                $change = $excess;
            } else {
                return new WP_Error(
                    'mx_pos_overpayment',
                    __('Overpayment can only be returned as cash change.', 'mx-pos-pro'),
                    ['status' => 400]
                );
            }
        }

        $transactionId = 'pos-mixed-' . $saleId;

        $this->set_order_payment_meta($order, 'mx_pos_mixed', __('Pago mixto', 'mx-pos-pro'), $clientRequestId, $transactionId);

        try {
            $this->complete_pos_order($order, $transactionId);
        } catch (\Exception $e) {
            $order->delete_meta_data('_mx_pos_payment_completed');
            $order->delete_meta_data('_mx_pos_payment_method');
            $order->delete_meta_data('_mx_pos_payment_method_title');
            $order->delete_meta_data('_mx_pos_payment_client_request_id');
            $order->delete_meta_data('_mx_pos_payment_transaction_id');
            $order->delete_meta_data('metodo_pago');
            $order->delete_meta_data('metodo_pago_nombre');
            $order->save();

            return new WP_Error(
                'mx_pos_payment_complete_failed',
                __('Payment could not be completed. Please try again.', 'mx-pos-pro'),
                ['status' => 500]
            );
        }

        $paidAt = $order->get_date_paid()
            ? $order->get_date_paid()->format('c')
            : current_time('c');

        $order->add_order_note(
            sprintf(
                /* translators: %1$d, %2$s are dynamic values generated by the plugin. */
                __('POS mixed payment: %1$d methods — $%2$s total.', 'mx-pos-pro'),
                count($normalizedLines),
                $this->formatDecimal($orderTotal)
            )
        );

        $order->save();

        $paymentInfo = [
            'method'          => $method['slug'],
            'method_name'     => $method['name'],
            'payment_lines'   => $normalizedLines,
            'total_paid'      => $this->formatDecimal($lineSum),
            'change'          => $this->formatDecimal($change),
            'card_fee_total'  => $totalCardFee > 0 ? $this->formatDecimal($totalCardFee) : '0.0000',
            'transaction_id'  => $transactionId,
            'paid_at'         => $paidAt,
            'cashier_id'      => $userId,
            'session_id'      => $sessionId,
        ];

        foreach ($normalizedLines as $i => $nl) {
            $this->write_order_payment(
                $saleId,
                $nl['method_id'],
                $nl['amount'],
                $nl['amount'],
                0,
                $nl['reference'],
                $transactionId,
                $clientRequestId . ':payment:' . $i
            );
        }

        $this->finalize_payment($sale, $saleId, $order, $paymentInfo, $sessionId, $userId);

        foreach ($normalizedLines as $i => $nl) {
            if ($nl['affects_cash_register']) {
                $cashAmount = $nl['amount'];
                if ($change > 0 && $nl['method'] === 'cash') {
                    $cashAmount -= $change;
                }
                if ($cashAmount > 0) {
                    $this->record_cash_movement(
                        $sessionId, $userId, $cashAmount,
                        (string) $order->get_order_number(),
                        $clientRequestId . ':cash-movement:' . $i
                    );
                }
            }
        }

        $this->saleRepo->create_log([
            'sale_id'    => $saleId,
            'event_type' => 'payment_received',
            'message'    => sprintf(
                /* translators: %s is a dynamic value generated by the plugin. */
                __('Mixed payment received — Order #%s.', 'mx-pos-pro'),
                $order->get_order_number()
            ),
            'created_by' => $userId,
        ]);

        $sale = $this->saleRepo->get_by_id($saleId);

        return $this->build_response($sale ?? [
            'id'              => $saleId,
            'session_id'      => $sessionId,
            'cashier_id'      => $userId,
            'created_at'      => current_time('mysql'),
            'payment_summary' => '',
        ], $order, $paymentInfo);
    }

    private function calculate_card_fee(array $method, float $amount): ?float
    {
        if (! (bool) ((int) ($method['card_fee_enabled'] ?? 0))) {
            return null;
        }

        $feeType  = $method['card_fee_type'] ?? null;
        $feeValue = isset($method['card_fee_value']) ? (float) $method['card_fee_value'] : 0;

        if ($feeType === null || $feeValue <= 0) {
            return null;
        }

        if ($feeType === 'percentage') {
            return round($amount * $feeValue / 100, 4);
        }

        if ($feeType === 'fixed') {
            return $feeValue;
        }

        return null;
    }

    private function set_order_payment_meta(
        \WC_Order $order,
        string $method,
        string $title,
        string $clientRequestId,
        string $transactionId
    ): void
    {
        WooOrderFactory::apply_payment_meta($order, $method, $title, $clientRequestId, $transactionId);
    }

    private function resolve_payment_method_title(array $method): string
    {
        if (! empty($method['wc_gateway_id'])) {
            return $method['name'];
        }

        return $method['name'];
    }

    private function write_order_payment(
        int $saleId, int $methodId, float $amount,
        float $tendered, float $change, ?string $reference, string $transactionId,
        string $clientRequestId
    ): void {
        global $wpdb;

        $table = $wpdb->prefix . 'mx_pos_order_payments';

        $paymentCrid = $clientRequestId . ':payment:0';

        $wpdb->insert(
            $table,
            [
                'sale_id'           => $saleId,
                'payment_method_id' => $methodId,
                'amount'            => $amount,
                'tendered_amount'   => $tendered,
                'change_amount'     => $change,
                'currency'          => 'MXN',
                'status'            => 'completed',
                'card_reference'    => $reference,
                'transaction_id'    => $transactionId,
                'client_request_id' => $paymentCrid,
                'created_at'        => current_time('mysql'),
                'updated_at'        => current_time('mysql'),
            ],
            ['%d', '%d', '%f', '%f', '%f', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
        );
    }

    private function finalize_payment(
        array $sale, int $saleId, \WC_Order $order,
        array $paymentInfo, int $sessionId, int $userId
    ): void {
        $existingSummary = $this->decode_payment_summary($sale['payment_summary'] ?? null);
        $existingSummary['tax_total'] = $existingSummary['tax_total'] ?? $this->formatDecimal(0);
        $existingSummary['payment']   = $paymentInfo;

        $encodedSummary = wp_json_encode($existingSummary);

        if (is_string($encodedSummary)) {
            $this->saleRepo->update_payment_summary($saleId, $encodedSummary);
        }

        $this->saleRepo->update_status($saleId, 'completed');
    }

    private function complete_pos_order(\WC_Order $order, string $transactionId): void
    {
        $order->payment_complete($transactionId);

        if ($order->get_status() !== 'completed') {
            $order->update_status(
                'completed',
                __('POS payment completed and fulfilled in-store.', 'mx-pos-pro'),
                true
            );
        }
    }

    private function record_cash_movement(int $sessionId, int $userId, float $amount, string $orderNumber, string $clientRequestId): void
    {
        try {
            $reason = sprintf('Venta POS — Orden #%s', $orderNumber);
            $crid   = $clientRequestId . ':cash-movement:0';

            $result = $this->cashMovementService->create_movement(
                $userId,
                'cash_in',
                $this->formatDecimal($amount),
                $reason,
                $crid
            );

            if (is_wp_error($result)) {
            }
        } catch (\Exception $e) {
        }
    }

    private function build_response(array $sale, \WC_Order $order, array $paymentInfo): array
    {
        $discountTotal = '0.0000';

        foreach ($order->get_fees() as $fee) {
            if ($fee->get_meta('_mx_pos_is_pos_discount', true) !== 'yes') {
                continue;
            }

            $discountTotal = $this->formatDecimal(abs((float) $fee->get_total()));
            break;
        }

        $couponTotal = 0.0;
        foreach ($order->get_coupons() as $couponItem) {
            $couponTotal += (float) $couponItem->get_discount();
        }

        return [
            'sale' => [
                'id'           => (int) $sale['id'],
                'order_id'     => $order->get_id(),
                'order_number' => (string) $order->get_order_number(),
                'status'       => $order->get_status(),
                'session_id'   => (int) ($sale['session_id'] ?? 0),
                'cashier_id'   => (int) ($sale['cashier_id'] ?? 0),
                'customer_id'  => $order->get_customer_id() > 0
                    ? $order->get_customer_id()
                    : null,
                'totals'       => [
                    'subtotal'       => $this->formatDecimal((float) $order->get_subtotal()),
                    'coupon_total'   => $this->formatDecimal($couponTotal),
                    'discount_total' => $discountTotal,
                    'total'          => $this->formatDecimal((float) $order->get_total()),
                ],
                'payment'      => $paymentInfo,
                'created_at'   => $sale['created_at'] ?? current_time('mysql'),
                'paid_at'      => $paymentInfo['paid_at'] ?? null,
            ],
        ];
    }

    private function decode_payment_summary(mixed $paymentSummary): array
    {
        if (! is_string($paymentSummary) || trim($paymentSummary) === '') {
            return [];
        }

        $decoded = json_decode($paymentSummary, true);

        return is_array($decoded) ? $decoded : [];
    }

    private function formatDecimal(float $value): string
    {
        return number_format($value, 4, '.', '');
    }
}
